### ISSUE TITLE
Searching for cases via the search term box does not work

### ISSUE THREAD

**Issue by xiamaz** [bihealth/varfish-server#1004] opened 2023-07-06 11:21 UTC
Entering an existing ID in the search term box on the header bar:

![image](https://github.com/bihealth/varfish-server/assets/3340720/eb5ccc1b-09ae-4158-82fc-cca58aee584e)

Does not find an existing sample. The ability to search for samples in the case list does not entirely replace this functionality, as searching across different projects a user can access is still important.

**Comment by holtgrewe** [comment] 2023-07-06 12:57
**Root Cause Analysis**
For the switch to the Vue.js based "cases" app, the code for the variants did not make it over.

**Comment by holtgrewe** [comment] 2023-07-06 13:39
PR will be merged soon, live in Berlin already.

**Closed** 2023-07-06 14:03 UTC
Labels: bug
