### ISSUE TITLE
Filter Variants For Case: Make number of shown tabs configurable

### ISSUE THREAD

**Issue by your-highness** [bihealth/varfish-server#830] opened 2023-01-25 15:25 UTC
**Is your feature request related to a problem? Please describe.**
View in "Filter Variants for Case" is currently very squished. More registers / tabs can be shown because there is space to show more tabs in filter view.
 
![image](https://user-images.githubusercontent.com/1949888/214603208-b154c310-b456-49af-9285-9acf3291b678.png)

**Describe the solution you'd like**
Configure the amount of tabs shown via an environment variable, for example.

**Describe alternatives you've considered**
none

**Additional context**
- @stolpeo 
- Please also backport to athenea if possible.

**Comment by stolpeo** [comment] 2023-01-25 15:52
@your-highness Thanks for the feature request. Configuration via variable would require some extensive coding as there is a bunch of javascript tied to that. I strongly opt for excluding that option. However, we can discuss putting some of the points from the `More` tab to the outside.

**Comment by your-highness** [comment] 2023-01-26 08:12
Thanks for you swift response!

Ok. _How can I do the following?_
1. Make "Prioritization" default tab on the left ( see #831 )
2. Enable tabs (**in that order**) "Genotype", "Gene List & Regions", "Frequency", "Variants Effects" & "Clinvar, HGMD & dbSNP"  after "Prioritization"
3. Remaining tabs can be listed under "More..."

**Comment by holtgrewe** [comment] 2023-07-24 15:03
Closing as duplicate of #830.

**Closed by holtgrewe** 2023-07-24 15:03 UTC
Labels: enhancement
